package com.example.radioplayer.utils

import com.example.radioplayer.adapters.models.CountryWithRegion


const val COUNTRY_REGION_AFRICA = "-AFRICA-"
const val COUNTRY_REGION_ASIA = "-ASIA-"
const val COUNTRY_REGION_CENTRAL_AMERICA = "-CENTRAL AMERICA-"
const val COUNTRY_REGION_NORTH_AMERICA = "-NORTH AMERICA-"
const val COUNTRY_REGION_SOUTH_AMERICA = "-SOUTH AMERICA-"
const val COUNTRY_REGION_EAST_EUROPE = "-EAST EUROPE-"
const val COUNTRY_REGION_WEST_EUROPE = "-WEST EUROPE-"
const val COUNTRY_REGION_MIDDLE_EAST = "-MIDDLE EAST-"
const val COUNTRY_REGION_OCEANIA = "-OCEANIA-"
const val COUNTRY_REGION_THE_CARIBBEAN = "-THE CARIBBEAN-"




    val listOfAfrica = setOf(
        CountryWithRegion.Country("Algeria", "DZ"),
        CountryWithRegion.Country("Angola", "AO"),
        CountryWithRegion.Country("Benin", "BJ"),
        CountryWithRegion.Country("Botswana", "BW"),
        CountryWithRegion.Country("Burkina Faso", "BF"),
        CountryWithRegion.Country("Burundi", "BI"),
        CountryWithRegion.Country("Cameroon", "CM"),
        CountryWithRegion.Country("Comoros", "KM"),
        CountryWithRegion.Country("Congo", "CD"),
        CountryWithRegion.Country("Coted Ivoire", "CI"),
        CountryWithRegion.Country("Egypt", "EG"),
        CountryWithRegion.Country("Equatorial Guinea", "GQ"),
        CountryWithRegion.Country("Eswatini", "SZ"),
        CountryWithRegion.Country("Ethiopia", "ET"),
        CountryWithRegion.Country("Ghana", "GH"),
        CountryWithRegion.Country("Guinea Bissau", "GW"),
        CountryWithRegion.Country("Kenya", "KE"),
        CountryWithRegion.Country("Libya", "LY"),
        CountryWithRegion.Country("Madagascar", "MG"),
        CountryWithRegion.Country("Malawi", "MW"),
        CountryWithRegion.Country("Mauritius", "MU"),
        CountryWithRegion.Country("Mayotte", "YT"),
        CountryWithRegion.Country("Morocco", "MA"),
        CountryWithRegion.Country("Mozambique", "MZ"),
        CountryWithRegion.Country("Namibia", "NA"),
        CountryWithRegion.Country("Nigeria", "NG"),
        CountryWithRegion.Country("Republic of Guinea", "GN"),
        CountryWithRegion.Country("Reunion", "RE"),
        CountryWithRegion.Country("Rwanda", "RW"),
        CountryWithRegion.Country("Saint Helena", "SH"),
        CountryWithRegion.Country("Sao Tome And Principe", "ST"),
        CountryWithRegion.Country("Senegal", "SN"),
        CountryWithRegion.Country("Seychelles", "SC"),
        CountryWithRegion.Country("Sierra Leone", "SL"),
        CountryWithRegion.Country("Somalia", "SO"),
        CountryWithRegion.Country("South Africa", "ZA"),
        CountryWithRegion.Country("Sudan", "SD"),
        CountryWithRegion.Country("Tanzania", "TZ"),
        CountryWithRegion.Country("The Central African Republic", "CF"),
        CountryWithRegion.Country("Togo", "TG"),
        CountryWithRegion.Country("Tunisia", "TN"),
        CountryWithRegion.Country("Uganda", "UG"),
        CountryWithRegion.Country("Zambia", "ZM"),
        CountryWithRegion.Country("Zimbabwe", "ZW"),
    )

    val listOfAsia = setOf(
        CountryWithRegion.Country("Afghanistan", "AF"),
        CountryWithRegion.Country("Armenia", "AM"),
        CountryWithRegion.Country("Azerbaijan", "AZ"),
        CountryWithRegion.Country("Bangladesh", "BD"),
        CountryWithRegion.Country("Bhutan", "BT"),
        CountryWithRegion.Country("Brunei Darussalam", "BN"),
        CountryWithRegion.Country("Cambodia", "KH"),
        CountryWithRegion.Country("China", "CN"),
        CountryWithRegion.Country("Georgia", "GE"),
        CountryWithRegion.Country("Hong Kong", "HK"),
        CountryWithRegion.Country("India", "IN"),
        CountryWithRegion.Country("Indonesia", "ID"),
        CountryWithRegion.Country("Japan", "JP"),
        CountryWithRegion.Country("Kazakhstan", "KZ"),
        CountryWithRegion.Country("Korea (North)", "KP"),
        CountryWithRegion.Country("Korea (South)", "KR"),
        CountryWithRegion.Country("Kyrgyzstan", "KG"),
        CountryWithRegion.Country("Macao", "MO"),
        CountryWithRegion.Country("Malaysia", "MY"),
        CountryWithRegion.Country("Mongolia", "MN"),
        CountryWithRegion.Country("Myanmar", "MM"),
        CountryWithRegion.Country("Nepal", "NP"),
        CountryWithRegion.Country("Pakistan", "PK"),
        CountryWithRegion.Country("Philippines", "PH"),
        CountryWithRegion.Country("Singapore", "SG"),
        CountryWithRegion.Country("Sri Lanka", "LK"),
        CountryWithRegion.Country("Taiwan", "TW"),
        CountryWithRegion.Country("Tajikistan", "TJ"),
        CountryWithRegion.Country("Thailand", "TH"),
        CountryWithRegion.Country("Turkmenistan", "TM"),
        CountryWithRegion.Country("Uzbekistan", "UZ"),
        CountryWithRegion.Country("Vietnam", "VN"),
    )

    val listOfCentralAmerica = setOf(
        CountryWithRegion.Country("Belize", "BZ"),
        CountryWithRegion.Country("Costa Rica", "CR"),
        CountryWithRegion.Country("El Salvador", "SV"),
        CountryWithRegion.Country("Guatemala", "GT"),
        CountryWithRegion.Country("Honduras", "HN"),
        CountryWithRegion.Country("Mexico", "MX"),
        CountryWithRegion.Country("Nicaragua", "NI"),
        CountryWithRegion.Country("Panama", "PA"),
    )


    val listOfEastEurope = setOf(
        CountryWithRegion.Country("Albania", "AL"),
        CountryWithRegion.Country("Belarus", "BY"),
        CountryWithRegion.Country("Bosnia And Herzegovina", "BA"),
        CountryWithRegion.Country("Bulgaria", "BG"),
        CountryWithRegion.Country("Croatia", "HR"),
        CountryWithRegion.Country("Czech Republic", "CZ"),
        CountryWithRegion.Country("Estonia", "EE"),
        CountryWithRegion.Country("Hungary", "HU"),
        CountryWithRegion.Country("Kosovo", "XK"),
        CountryWithRegion.Country("Latvia", "LV"),
        CountryWithRegion.Country("Lithuania", "LT"),
        CountryWithRegion.Country("Moldova", "MD"),
        CountryWithRegion.Country("Montenegro", "ME"),
        CountryWithRegion.Country("North Macedonia", "MK"),
        CountryWithRegion.Country("Poland", "PL"),
        CountryWithRegion.Country("Romania", "RO"),
        CountryWithRegion.Country("Russia", "RU"),
        CountryWithRegion.Country("Serbia", "RS"),
        CountryWithRegion.Country("Slovakia", "SK"),
        CountryWithRegion.Country("Turkey", "TR"),
        CountryWithRegion.Country("Ukraine", "UA"),
    )

    val listOfWestEurope = setOf(
        CountryWithRegion.Country("Andorra", "AD"),
        CountryWithRegion.Country("Austria", "AT"),
        CountryWithRegion.Country("Belgium", "BE"),
        CountryWithRegion.Country("Denmark", "DK"),
        CountryWithRegion.Country("Faroe Islands", "FO"),
        CountryWithRegion.Country("Finland", "FI"),
        CountryWithRegion.Country("France", "FR"),
        CountryWithRegion.Country("Germany", "DE"),
        CountryWithRegion.Country("Gibraltar", "GI"),
        CountryWithRegion.Country("Greece", "GR"),
        CountryWithRegion.Country("Guernsey", "GG"),
        CountryWithRegion.Country("Iceland", "IS"),
        CountryWithRegion.Country("Ireland", "IE"),
        CountryWithRegion.Country("Isle Of Man", "IM"),
        CountryWithRegion.Country("Italy", "IT"),
        CountryWithRegion.Country("Jersey", "JE"),
        CountryWithRegion.Country("Liechtenstein", "LI"),
        CountryWithRegion.Country("Luxembourg", "LU"),
        CountryWithRegion.Country("Malta", "MT"),
        CountryWithRegion.Country("Monaco", "MC"),
        CountryWithRegion.Country("Netherlands", "NL"),
        CountryWithRegion.Country("Norway", "NO"),
        CountryWithRegion.Country("Portugal", "PT"),
        CountryWithRegion.Country("San Marino", "SM"),
        CountryWithRegion.Country("Slovenia", "SI"),
        CountryWithRegion.Country("Spain", "ES"),
        CountryWithRegion.Country("Sweden", "SE"),
        CountryWithRegion.Country("Switzerland", "CH"),
        CountryWithRegion.Country("The United Kingdom Of Great Britain And Northern Ireland", "GB"),
        CountryWithRegion.Country("Vatican City", "VA"),
        )

    val listOfMiddleEast = setOf(
        CountryWithRegion.Country("Bahrain", "BH"),
        CountryWithRegion.Country("Cyprus", "CY"),
        CountryWithRegion.Country("Iran", "IR"),
        CountryWithRegion.Country("Iraq", "IQ"),
        CountryWithRegion.Country("Israel", "IL"),
        CountryWithRegion.Country("Jordan", "JO"),
        CountryWithRegion.Country("Kuwait", "KW"),
        CountryWithRegion.Country("Lebanon", "LB"),
        CountryWithRegion.Country("Oman", "OM"),
        CountryWithRegion.Country("Palestine", "PS"),
        CountryWithRegion.Country("Qatar", "QA"),
        CountryWithRegion.Country("Saudi Arabia", "SA"),
        CountryWithRegion.Country("Syria", "SY"),
        CountryWithRegion.Country("United Arab Emirates", "AE"),
        CountryWithRegion.Country("Yemen", "YE"),
    )

    val listOfNorthAmerica = setOf(
        CountryWithRegion.Country("Bermuda", "BM"),
        CountryWithRegion.Country("Canada", "CA"),
        CountryWithRegion.Country("Greenland", "GL"),
        CountryWithRegion.Country("Saint Pierre And Miquelon", "PM"),
        CountryWithRegion.Country("The United States Of America", "US"),
    )

    val listOfOceania = setOf(
        CountryWithRegion.Country("American Samoa", "AS"),
        CountryWithRegion.Country("Antarctica", "AQ"),
        CountryWithRegion.Country("Australia", "AU"),
        CountryWithRegion.Country("British Indian Ocean Territory", "IO"),
        CountryWithRegion.Country("Cabo Verde", "CV"),
        CountryWithRegion.Country("Fiji", "FJ"),
        CountryWithRegion.Country("French Polynesia", "PF"),
        CountryWithRegion.Country("Guam", "GU"),
        CountryWithRegion.Country("Kiribati", "KI"),
        CountryWithRegion.Country("New Caledonia", "NC"),
        CountryWithRegion.Country("New Zealand", "NZ"),
        CountryWithRegion.Country("Norfolk Island", "NF"),
        CountryWithRegion.Country("South Georgia And The South Sandwich Islands", "GS"),
        CountryWithRegion.Country("The Cocos Keeling Islands", "CC"),
        CountryWithRegion.Country("The Cook Islands", "CK"),
        CountryWithRegion.Country("The French Southern Territories", "TF"),
        CountryWithRegion.Country("Tonga", "TO"),
        CountryWithRegion.Country("United States Minor Outlying Islands", "UM"),
        CountryWithRegion.Country("Vanuatu", "VU"),
        CountryWithRegion.Country("Wallis And Futuna", "WF"),
    )

    val listOfSouthAmerica = setOf(
        CountryWithRegion.Country("Argentina", "AR"),
        CountryWithRegion.Country("Bolivia", "BO"),
        CountryWithRegion.Country("Brazil", "BR"),
        CountryWithRegion.Country("Chile", "CL"),
        CountryWithRegion.Country("Colombia", "CO"),
        CountryWithRegion.Country("Ecuador", "EC"),
        CountryWithRegion.Country("French Guiana", "GF"),
        CountryWithRegion.Country("Guyana", "GY"),
        CountryWithRegion.Country("Paraguay", "PY"),
        CountryWithRegion.Country("Peru", "PE"),
        CountryWithRegion.Country("Suriname", "SR"),
        CountryWithRegion.Country("The Falkland Islands (Malvinas)", "FK"),
        CountryWithRegion.Country("Uruguay", "UY"),
        CountryWithRegion.Country("Venezuela", "VE"),
    )

    val listOfTheCaribbean = setOf(
        CountryWithRegion.Country("Antigua And Barbuda", "AG"),
        CountryWithRegion.Country("Aruba", "AW"),
        CountryWithRegion.Country("Bahamas", "BS"),
        CountryWithRegion.Country("Barbados", "BB"),
        CountryWithRegion.Country("Bonaire", "BQ"),
        CountryWithRegion.Country("Cayman Islands", "KY"),
        CountryWithRegion.Country("Cuba", "CU"),
        CountryWithRegion.Country("Curacao", "CW"),
        CountryWithRegion.Country("Dominica", "DM"),
        CountryWithRegion.Country("Dominican Republic", "DO"),
        CountryWithRegion.Country("Grenada", "GD"),
        CountryWithRegion.Country("Guadeloupe", "GP"),
        CountryWithRegion.Country("Haiti", "HT"),
        CountryWithRegion.Country("Jamaica", "JM"),
        CountryWithRegion.Country("Martinique", "MQ"),
        CountryWithRegion.Country("Puerto Rico", "PR"),
        CountryWithRegion.Country("Saint Kitts And Nevis", "KN"),
        CountryWithRegion.Country("Saint Lucia", "LC"),
        CountryWithRegion.Country("Saint Vincent And The Grenadines", "VC"),
        CountryWithRegion.Country("Trinidad And Tobago", "TT"),
        CountryWithRegion.Country("Turks And Caicos Islands", "TC"),
        CountryWithRegion.Country("US Virgin Islands", "VI"),
    )




//    val listOfCountries = listOf(
//
//        Country("Suriname", "SR"),
//        Country("Sao Tome And Principe", "ST"),
//        Country("El Salvador", "SV"),
//        Country("Syrian Arab Republic", "SY"),
//        Country("Eswatini", "SZ"),
//        Country("The Turks And Caicos Islands", "TC"),
//        Country("The French Southern Territories", "TF"),
//        Country("Togo", "TG"),
//        Country("Tajikistan", "TJ"),
//        Country("Thailand", "TH"),
//        Country("Turkmenistan", "TM"),
//        Country("Uzbekistan", "UZ"),
//        Country("Vietnam", "VN"),
//        Country("Tunisia", "TN"),
//        Country("Tonga", "TO"),
//        Country("Turkey", "TR"),
//        Country("Ukraine", "UA"),
//        Country("Trinidad And Tobago", "TT"),
//        Country("Taiwan", "TW"),
//        Country("Tanzania", "TZ"),
//        Country("Uganda", "UG"),
//        Country("Zambia", "ZM"),
//        Country("Zimbabwe", "ZW"),
//        Country("United States Minor Outlying Islands", "UM"),
//        Country("The United States Of America", "US"),
//        Country("Uruguay", "UY"),
//        Country("Vatican City", "VA"),
//        Country("Saint Vincent And The Grenadines", "VC"),
//        Country("Venezuela", "VE"),
//        Country("US Virgin Islands", "VI"),
//        Country("Vanuatu", "VU"),
//        Country("Wallis And Futuna", "WF"),
//        Country("Kosovo", "XK"),
//        Country("Yemen", "YE"),
//        Country("Mayotte", "YT"),
//        Country("South Africa", "ZA"),
//
//
//
//                Country("Andorra", "AD"),
//        Country("The United Arab Emirates", "AE"),
//        Country("Afghanistan", "AF"),
//        Country("Antigua And Barbuda", "AG"),
//        Country("Albania", "AL"),
//        Country("Armenia", "AM"),
//        Country("Angola", "AO"),
//        Country("Antarctica", "AQ"),
//        Country("Argentina", "AR"),
//        Country("American Samoa", "AS"),
//        Country("Austria", "AT"),
//        Country("Australia", "AU"),
//        Country("Aruba", "AW"),
//        Country("Azerbaijan", "AZ"),
//        Country("Bosnia And Herzegovina", "BA"),
//        Country("Barbados", "BB"),
//        Country("Bangladesh", "BD"),
//        Country("Belgium", "BE"),
//        Country("Burkina Faso", "BF"),
//        Country("Bulgaria", "BG"),
//        Country("Bahrain", "BH"),
//        Country("Burundi", "BI"),
//        Country("Benin", "BJ"),
//        Country("Bermuda", "BM"),
//        Country("Brunei Darussalam", "BN"),
//        Country("Bolivia", "BO"),
//        Country("Bonaire", "BQ"),
//        Country("Brazil", "BR"),
//        Country("The Bahamas", "BS"),
//        Country("Bhutan", "BT"),
//        Country("Botswana", "BW"),
//        Country("Belarus", "BY"),
//        Country("Belize", "BZ"),
//        Country("Canada", "CA"),
//        Country("The Cocos Keeling Islands", "CC"),
//        Country("The Democratic Republic Of The Congo", "CD"),
//        Country("The Central African Republic", "CF"),
//        Country("Switzerland", "CH"),
//        Country("Coted Ivoire", "CI"),
//        Country("The Cook Islands", "CK"),
//        Country("Chile", "CL"),
//        Country("Cameroon", "CM"),
//        Country("China", "CN"),
//        Country("Colombia", "CO"),
//        Country("Costa Rica", "CR"),
//        Country("Cuba", "CU"),
//        Country("Cabo Verde", "CV"),
//        Country("Curacao", "CW"),
//        Country("Cyprus", "CY"),
//        Country("Czech Republic", "CZ"),
//        Country("Dominica", "DM"),
//        Country("The Dominican Republic", "DO"),
//        Country("Algeria", "DZ"),
//        Country("Ecuador", "EC"),
//        Country("Estonia", "EE"),
//        Country("Egypt", "EG"),
//        Country("Spain", "ES"),
//        Country("Ethiopia", "ET"),
//        Country("Finland", "FI"),
//        Country("Fiji", "FJ"),
//        Country("The Falkland Islands (Malvinas)", "FK"),
//        Country("The Faroe Islands", "FO"),
//        Country("France", "FR"),
//        Country("The United Kingdom Of Great Britain And Northern Ireland", "GB"),
//        Country("Grenada", "GD"),
//        Country("Georgia", "GE"),
//        Country("French Guiana", "GF"),
//        Country("Guernsey", "GG"),
//        Country("Ghana", "GH"),
//        Country("Gibraltar", "GI"),
//        Country("Greenland", "GL"),
//        Country("Guinea", "GN"),
//        Country("Guadeloupe", "GP"),
//        Country("Equatorial Guinea", "GQ"),
//        Country("Greece", "GR"),
//        Country("South Georgia And The South Sandwich Islands", "GS"),
//        Country("Guatemala", "GT"),
//        Country("Guam", "GU"),
//        Country("Guinea Bissau", "GW"),
//        Country("Guyana", "GY"),
//        Country("Hong Kong", "HK"),
//        Country("Honduras", "HN"),
//        Country("Croatia", "HR"),
//        Country("Haiti", "HT"),
//        Country("Hungary", "HU"),
//        Country("Indonesia", "ID"),
//        Country("Ireland", "IE"),
//        Country("Israel", "IL"),
//        Country("Isle Of Man", "IM"),
//        Country("India", "IN"),
//        Country("British Indian Ocean Territory", "IO"),
//        Country("Iraq", "IQ"),
//        Country("Islamic Republic Of Iran", "IR"),
//        Country("Iceland", "IS"),
//        Country("Italy", "IT"),
//        Country("Jersey", "JE"),
//        Country("Jamaica", "JM"),
//        Country("Jordan", "JO"),
//        Country("Japan", "JP"),
//        Country("Kenya", "KE"),
//        Country("Kyrgyzstan", "KG"),
//        Country("Cambodia", "KH"),
//        Country("Kiribati", "KI"),
//        Country("Saint Kitts And Nevis", "KN"),
//        Country("Korea (North)", "KP"),
//        Country("Korea (South)", "KR"),
//        Country("Kuwait", "KW"),
//        Country("The Cayman Islands", "KY"),
//        Country("Kazakhstan", "KZ"),
//        Country("Lebanon", "LB"),
//        Country("Saint Lucia", "LC"),
//        Country("Liechtenstein", "LI"),
//        Country("Sri Lanka", "LK"),
//        Country("Libya", "LY"),
//        Country("Morocco", "MA"),
//        Country("Monaco", "MC"),
//        Country("The Republic Of Moldova", "MD"),
//        Country("Montenegro", "ME"),
//        Country("Madagascar", "MG"),
//        Country("North Macedonia", "MK"),
//        Country("Myanmar", "MM"),
//        Country("Mongolia", "MN"),
//        Country("Macao", "MO"),
//        Country("Martinique", "MQ"),
//        Country("Malta", "MT"),
//        Country("Mauritius", "MU"),
//        Country("Malawi", "MW"),
//        Country("Mexico", "MX"),
//        Country("Malaysia", "MY"),
//        Country("Mozambique", "MZ"),
//        Country("Namibia", "NA"),
//        Country("New Caledonia", "NC"),
//        Country("Norfolk Island", "NF"),
//        Country("Nigeria", "NG"),
//        Country("Nicaragua", "NI"),
//        Country("Netherlands", "NL"),
//        Country("Norway", "NO"),
//        Country("Nepal", "NP"),
//        Country("New Zealand", "NZ"),
//        Country("Oman", "OM"),
//        Country("Panama", "PA"),
//        Country("Peru", "PE"),
//        Country("French Polynesia", "PF"),
//        Country("The Philippines", "PH"),
//        Country("Pakistan", "PK"),
//        Country("Poland", "PL"),
//        Country("Saint Pierre And Miquelon", "PM"),
//        Country("Puerto Rico", "PR"),
//        Country("Palestine", "PS"),
//        Country("Portugal", "PT"),
//        Country("Paraguay", "PY"),
//        Country("Qatar", "QA"),
//        Country("Reunion", "RE"),
//        Country("Rwanda", "RW"),
//        Country("Seychelles", "SC"),
//        Country("Sudan", "SD"),
//        Country("Romania", "RO"),
//        Country("Slovenia", "SI"),
//        Country("Slovakia", "SK"),
//        Country("Sweden", "SE"),
//        Country("Serbia", "RS"),
//        Country("Russia", "RU"),
//        Country("Saudi Arabia", "SA"),
//        Country("Singapore", "SG"),
//        Country("Saint Helena", "SH"),
//        Country("Sierra Leone", "SL"),
//        Country("San Marino", "SM"),
//        Country("Senegal", "SN"),
//        Country("Somalia", "SO"),
//
//
//)


//val listOfCountryNames = listOf("Andorra", "The United Arab Emirates", "Afghanistan",
//    "Antigua And Barbuda", "Albania", "Armenia", "Angola", "Antarctica", "Argentina",
//    "American Samoa", "Austria", "Australia", "Aruba", "Azerbaijan", "Bosnia And Herzegovina",
//    "Barbados", "Bangladesh", "Belgium", "Burkina Faso", "Bulgaria", "Bahrain", "Burundi", "Benin",
//    "Bermuda", "Brunei Darussalam", "Bolivia", "Bonaire", "Brazil", "The Bahamas", "Bhutan",
//    "Botswana", "Belarus", "Belize", "Canada", "The Cocos Keeling Islands",
//    "The Democratic Republic Of The Congo", "The Central African Republic",
//    "Switzerland", "Coted Ivoire", "The Cook Islands", "Chile", "Cameroon", "China",
//    "Colombia", "Costa Rica", "Cuba", "Cabo Verde", "Curacao", "Cyprus", "Czechia", "Germany",
//    "Denmark", "Dominica", "The Dominican Republic", "Algeria", "Ecuador", "Estonia", "Egypt",
//    "Spain", "Ethiopia", "Finland", "Fiji", "The Falkland Islands Malvinas", "The Faroe Islands",
//    "France", "The United Kingdom Of Great Britain And Northern Ireland", "Grenada", "Georgia",
//    "French Guiana", "Guernsey", "Ghana", "Gibraltar", "Greenland", "Guinea", "Guadeloupe",
//    "Equatorial Guinea", "Greece", "South Georgia And The South Sandwich Islands", "Guatemala",
//    "Guam", "Guinea Bissau", "Guyana", "Hong Kong", "Honduras", "Croatia", "Haiti", "Hungary",
//    "Indonesia", "Ireland", "Israel", "Isle Of Man", "India", "British Indian Ocean Territory",
//    "Iraq", "Islamic Republic Of Iran", "Iceland", "Italy", "Jersey", "Jamaica", "Jordan", "Japan",
//    "Kenya", "Kyrgyzstan", "Cambodia", "Kiribati", "The Comoros", "Saint Kitts And Nevis",
//    "The Democratic Peoples Republic Of Korea", "The Republic Of Korea", "Kuwait",
//    "The Cayman Islands", "Kazakhstan", "Lebanon", "Saint Lucia", "Liechtenstein",
//    "Sri Lanka", "Lithuania", "Luxembourg", "Latvia", "Libya", "Morocco", "Monaco",
//    "The Republic Of Moldova", "Montenegro", "Madagascar", "Republic Of North Macedonia",
//    "Myanmar", "Mongolia", "Macao", "Martinique", "Malta", "Mauritius", "Malawi", "Mexico",
//    "Malaysia", "Mozambique", "Namibia", "New Caledonia", "Norfolk Island", "Nigeria", "Nicaragua",
//    "The Netherlands", "Norway", "Nepal", "New Zealand", "Oman", "Panama", "Peru",
//    "French Polynesia", "The Philippines", "Pakistan", "Poland", "Saint Pierre And Miquelon",
//    "Puerto Rico", "State Of Palestine", "Portugal", "Paraguay", "Qatar", "Reunion", "Romania",
//    "Serbia", "The Russian Federation", "Rwanda", "Saudi Arabia", "Seychelles", "The Sudan",
//    "Sweden", "Singapore", "Ascension And Tristan Da Cunha Saint Helena", "Slovenia", "Slovakia",
//    "Sierra Leone", "San Marino", "Senegal", "Somalia", "Suriname", "Sao Tome And Principe",
//    "El Salvador", "Syrian Arab Republic", "Eswatini", "The Turks And Caicos Islands",
//    "The French Southern Territories", "Togo", "Thailand", "Tajikistan", "Turkmenistan",
//    "Tunisia", "Tonga", "Turkey", "Trinidad And Tobago", "Taiwan Province Of China",
//    "United Republic Of Tanzania", "Ukraine", "Uganda", "The United States Minor Outlying Islands",
//    "The United States Of America", "Uruguay", "Uzbekistan", "The Holy See",
//    "Saint Vincent And The Grenadines", "Bolivarian Republic Of Venezuela",
//    "US Virgin Islands", "Vietnam", "Vanuatu", "Wallis And Futuna", "Kosovo",
//    "Yemen", "Mayotte", "South Africa", "Zambia", "Zimbabwe"
//)
//
//    val listOfCountryCodes = listOf(
//        "AD", "AE", "AF", "AG", "AL", "AM", "AO", "AQ", "AR", "AS", "AT", "AU",
//        "AW", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BM",
//        "BN", "BO", "BQ", "BR", "BS", "BT", "BW", "BY", "BZ", "CA", "CC", "CD",
//        "CF", "CH", "CI", "CK", "CL", "CM", "CN", "CO", "CR", "CU", "CV", "CW",
//        "CY", "CZ", "DE", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "ES", "ET",
//        "FI", "FJ", "FK", "FO", "FR", "GB", "GD", "GE", "GF", "GG", "GH", "GI",
//        "GL", "GN", "GP", "GQ", "GR", "GS", "GT", "GU", "GW", "GY", "HK", "HN",
//        "HR", "HT", "HU", "ID", "IE", "IL", "IM", "IN", "IO", "IQ", "IR", "IS",
//        "IT", "JE", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KP",
//        "KR", "KW", "KY", "KZ", "LB", "LC", "LI", "LK", "LT", "LU", "LV", "LY",
//        "MA", "MC", "MD", "ME", "MG", "MK", "MM", "MN", "MO", "MQ", "MT", "MU",
//        "MW", "MX", "MY", "MZ", "NA", "NC", "NF", "NG", "NI", "NL", "NO", "NP",
//        "NZ", "OM", "PA", "PE", "PF", "PH", "PK", "PL", "PM", "PR", "PS", "PT",
//        "PY", "QA", "RE", "RO", "RS", "RU", "RW", "SA", "SC", "SD", "SE", "SG",
//        "SH", "SI", "SK", "SL", "SM", "SN", "SO", "SR", "ST", "SV", "SY", "SZ",
//        "TC", "TF", "TG", "TH", "TJ", "TM", "TN", "TO", "TR", "TT", "TW", "TZ",
//        "UA", "UG", "UM", "US", "UY", "UZ", "VA", "VC", "VE", "VI", "VN", "VU",
//        "WF", "XK", "YE", "YT", "ZM", "ZW"
//    )