package com.example.radioplayer.utils

data class Country(
    val countryName : String,
    val countryCode : String
)

    val listOfCountries = listOf(
        Country("Andorra", "AD"),
        Country("The United Arab Emirates", "AE"),
        Country("Afghanistan", "AF"),
        Country("Antigua And Barbuda", "AG"),
        Country("Albania", "AL"),
        Country("Armenia", "AM"),
        Country("Angola", "AO"),
        Country("Antarctica", "AQ"),
        Country("Argentina", "AR"),
        Country("American Samoa", "AS"),
        Country("Austria", "AT"),
        Country("Australia", "AU"),
        Country("Aruba", "AW"),
        Country("Azerbaijan", "AZ"),
        Country("Bosnia And Herzegovina", "BA"),
        Country("Barbados", "BB"),
        Country("Bangladesh", "BD"),
        Country("Belgium", "BE"),
        Country("Burkina Faso", "BF"),
        Country("Bulgaria", "BG"),
        Country("Bahrain", "BH"),
        Country("Burundi", "BI"),
        Country("Benin", "BJ"),
        Country("Bermuda", "BM"),
        Country("Brunei Darussalam", "BN"),
        Country("Bolivia", "BO"),
        Country("Bonaire", "BQ"),
        Country("Brazil", "BR"),
        Country("The Bahamas", "BS"),
        Country("Bhutan", "BT"),
        Country("Botswana", "BW"),
        Country("Belarus", "BY"),
        Country("Belize", "BZ"),
        Country("Canada", "CA"),
        Country("The Cocos Keeling Islands", "CC"),
        Country("The Democratic Republic Of The Congo", "CD"),
        Country("The Central African Republic", "CF"),
        Country("Switzerland", "CH"),
        Country("Coted Ivoire", "CI"),
        Country("The Cook Islands", "CK"),
        Country("Chile", "CL"),
        Country("Cameroon", "CM"), Country("China", "CN"), Country("Colombia", "CO"), Country("Costa Rica", "CR"),
        Country("Cuba", "CU"), Country("Cabo Verde", "CV"), Country("Curacao", "CW"), Country("Cyprus", "CY"), Country("Czechia", "CZ"), Country("Germany", "DE"), Country("Denmark", "DK"), Country("Dominica", "DM"), Country("The Dominican Republic", "DO"), Country("Algeria", "DZ"), Country("Ecuador", "EC"), Country("Estonia", "EE"), Country("Egypt", "EG"), Country("Spain", "ES"), Country("Ethiopia", "ET"), Country("Finland", "FI"), Country("Fiji", "FJ"), Country("The Falkland Islands Malvinas", "FK"), Country("The Faroe Islands", "FO"), Country("France", "FR"), Country("The United Kingdom Of Great Britain And Northern Ireland", "GB"), Country("Grenada", "GD"), Country("Georgia", "GE"), Country("French Guiana", "GF"), Country("Guernsey", "GG"), Country("Ghana", "GH"), Country("Gibraltar", "GI"), Country("Greenland", "GL"), Country("Guinea", "GN"), Country("Guadeloupe", "GP"), Country("Equatorial Guinea", "GQ"), Country("Greece", "GR"), Country("South Georgia And The South Sandwich Islands", "GS"), Country("Guatemala", "GT"), Country("Guam", "GU"), Country("Guinea Bissau", "GW"), Country("Guyana", "GY"), Country("Hong Kong", "HK"), Country("Honduras", "HN"), Country("Croatia", "HR"), Country("Haiti", "HT"), Country("Hungary", "HU"), Country("Indonesia", "ID"), Country("Ireland", "IE"), Country("Israel", "IL"),
        Country("Isle Of Man", "IM"), Country("India", "IN"), Country("British Indian Ocean Territory", "IO"), Country("Iraq", "IQ"), Country("Islamic Republic Of Iran", "IR"), Country("Iceland", "IS"), Country("Italy", "IT"), Country("Jersey", "JE"), Country("Jamaica", "JM"), Country("Jordan", "JO"), Country("Japan", "JP"), Country("Kenya", "KE"), Country("Kyrgyzstan", "KG"), Country("Cambodia", "KH"), Country("Kiribati", "KI"), Country("The Comoros", "KM"), Country("Saint Kitts And Nevis", "KN"), Country("The Democratic Peoples Republic Of Korea", "KP"), Country("The Republic Of Korea", "KR"), Country("Kuwait", "KW"), Country("The Cayman Islands", "KY"), Country("Kazakhstan", "KZ"), Country("Lebanon", "LB"), Country("Saint Lucia", "LC"), Country("Liechtenstein", "LI"), Country("Sri Lanka", "LK"), Country("Lithuania", "LT"), Country("Luxembourg", "LU"), Country("Latvia", "LV"), Country("Libya", "LY"), Country("Morocco", "MA"), Country("Monaco", "MC"), Country("The Republic Of Moldova", "MD"), Country("Montenegro", "ME"), Country("Madagascar", "MG"), Country("Republic Of North Macedonia", "MK"), Country("Myanmar", "MM"), Country("Mongolia", "MN"), Country("Macao", "MO"), Country("Martinique", "MQ"), Country("Malta", "MT"), Country("Mauritius", "MU"), Country("Malawi", "MW"), Country("Mexico", "MX"), Country("Malaysia", "MY"),
        Country("Mozambique", "MZ"), Country("Namibia", "NA"), Country("New Caledonia", "NC"), Country("Norfolk Island", "NF"), Country("Nigeria", "NG"), Country("Nicaragua", "NI"), Country("The Netherlands", "NL"), Country("Norway", "NO"), Country("Nepal", "NP"), Country("New Zealand", "NZ"), Country("Oman", "OM"), Country("Panama", "PA"), Country("Peru", "PE"), Country("French Polynesia", "PF"), Country("The Philippines", "PH"), Country("Pakistan", "PK"), Country("Poland", "PL"), Country("Saint Pierre And Miquelon", "PM"), Country("Puerto Rico", "PR"), Country("State Of Palestine", "PS"), Country("Portugal", "PT"), Country("Paraguay", "PY"), Country("Qatar", "QA"), Country("Reunion", "RE"), Country("Romania", "RO"), Country("Serbia", "RS"), Country("The Russian Federation", "RU"), Country("Rwanda", "RW"), Country("Saudi Arabia", "SA"), Country("Seychelles", "SC"), Country("The Sudan", "SD"), Country("Sweden", "SE"), Country("Singapore", "SG"), Country("Ascension And Tristan Da Cunha Saint Helena", "SH"), Country("Slovenia", "SI"), Country("Slovakia", "SK"), Country("Sierra Leone", "SL"), Country("San Marino", "SM"), Country("Senegal", "SN"), Country("Somalia", "SO"),
        Country("Suriname", "SR"), Country("Sao Tome And Principe", "ST"), Country("El Salvador", "SV"), Country("Syrian Arab Republic", "SY"), Country("Eswatini", "SZ"), Country("The Turks And Caicos Islands", "TC"), Country("The French Southern Territories", "TF"), Country("Togo", "TG"), Country("Thailand", "TH"), Country("Tajikistan", "TJ"), Country("Turkmenistan", "TM"), Country("Tunisia", "TN"), Country("Tonga", "TO"), Country("Turkey", "TR"), Country("Trinidad And Tobago", "TT"), Country("Taiwan Province Of China", "TW"), Country("United Republic Of Tanzania", "TZ"), Country("Ukraine", "UA"), Country("Uganda", "UG"), Country("The United States Minor Outlying Islands", "UM"), Country("The United States Of America", "US"), Country("Uruguay", "UY"), Country("Uzbekistan", "UZ"), Country("The Holy See", "VA"), Country("Saint Vincent And The Grenadines", "VC"), Country("Bolivarian Republic Of Venezuela", "VE"), Country("US Virgin Islands", "VI"), Country("Vietnam", "VN"), Country("Vanuatu", "VU"), Country("Wallis And Futuna", "WF"), Country("Kosovo", "XK"), Country("Yemen", "YE"), Country("Mayotte", "YT"), Country("South Africa", "ZA"), Country("Zambia", "ZM"), Country("Zimbabwe", "ZW")

)


//val listOfCountryNames = listOf("Andorra", "The United Arab Emirates", "Afghanistan",
//    "Antigua And Barbuda", "Albania", "Armenia", "Angola", "Antarctica", "Argentina",
//    "American Samoa", "Austria", "Australia", "Aruba", "Azerbaijan", "Bosnia And Herzegovina",
//    "Barbados", "Bangladesh", "Belgium", "Burkina Faso", "Bulgaria", "Bahrain", "Burundi", "Benin",
//    "Bermuda", "Brunei Darussalam", "Bolivia", "Bonaire", "Brazil", "The Bahamas", "Bhutan",
//    "Botswana", "Belarus", "Belize", "Canada", "The Cocos Keeling Islands",
//    "The Democratic Republic Of The Congo", "The Central African Republic",
//    "Switzerland", "Coted Ivoire", "The Cook Islands", "Chile", "Cameroon", "China",
//    "Colombia", "Costa Rica", "Cuba", "Cabo Verde", "Curacao", "Cyprus", "Czechia", "Germany",
//    "Denmark", "Dominica", "The Dominican Republic", "Algeria", "Ecuador", "Estonia", "Egypt",
//    "Spain", "Ethiopia", "Finland", "Fiji", "The Falkland Islands Malvinas", "The Faroe Islands",
//    "France", "The United Kingdom Of Great Britain And Northern Ireland", "Grenada", "Georgia",
//    "French Guiana", "Guernsey", "Ghana", "Gibraltar", "Greenland", "Guinea", "Guadeloupe",
//    "Equatorial Guinea", "Greece", "South Georgia And The South Sandwich Islands", "Guatemala",
//    "Guam", "Guinea Bissau", "Guyana", "Hong Kong", "Honduras", "Croatia", "Haiti", "Hungary",
//    "Indonesia", "Ireland", "Israel", "Isle Of Man", "India", "British Indian Ocean Territory",
//    "Iraq", "Islamic Republic Of Iran", "Iceland", "Italy", "Jersey", "Jamaica", "Jordan", "Japan",
//    "Kenya", "Kyrgyzstan", "Cambodia", "Kiribati", "The Comoros", "Saint Kitts And Nevis",
//    "The Democratic Peoples Republic Of Korea", "The Republic Of Korea", "Kuwait",
//    "The Cayman Islands", "Kazakhstan", "Lebanon", "Saint Lucia", "Liechtenstein",
//    "Sri Lanka", "Lithuania", "Luxembourg", "Latvia", "Libya", "Morocco", "Monaco",
//    "The Republic Of Moldova", "Montenegro", "Madagascar", "Republic Of North Macedonia",
//    "Myanmar", "Mongolia", "Macao", "Martinique", "Malta", "Mauritius", "Malawi", "Mexico",
//    "Malaysia", "Mozambique", "Namibia", "New Caledonia", "Norfolk Island", "Nigeria", "Nicaragua",
//    "The Netherlands", "Norway", "Nepal", "New Zealand", "Oman", "Panama", "Peru",
//    "French Polynesia", "The Philippines", "Pakistan", "Poland", "Saint Pierre And Miquelon",
//    "Puerto Rico", "State Of Palestine", "Portugal", "Paraguay", "Qatar", "Reunion", "Romania",
//    "Serbia", "The Russian Federation", "Rwanda", "Saudi Arabia", "Seychelles", "The Sudan",
//    "Sweden", "Singapore", "Ascension And Tristan Da Cunha Saint Helena", "Slovenia", "Slovakia",
//    "Sierra Leone", "San Marino", "Senegal", "Somalia", "Suriname", "Sao Tome And Principe",
//    "El Salvador", "Syrian Arab Republic", "Eswatini", "The Turks And Caicos Islands",
//    "The French Southern Territories", "Togo", "Thailand", "Tajikistan", "Turkmenistan",
//    "Tunisia", "Tonga", "Turkey", "Trinidad And Tobago", "Taiwan Province Of China",
//    "United Republic Of Tanzania", "Ukraine", "Uganda", "The United States Minor Outlying Islands",
//    "The United States Of America", "Uruguay", "Uzbekistan", "The Holy See",
//    "Saint Vincent And The Grenadines", "Bolivarian Republic Of Venezuela",
//    "US Virgin Islands", "Vietnam", "Vanuatu", "Wallis And Futuna", "Kosovo",
//    "Yemen", "Mayotte", "South Africa", "Zambia", "Zimbabwe"
//)
//
//    val listOfCountryCodes = listOf(
//        "AD", "AE", "AF", "AG", "AL", "AM", "AO", "AQ", "AR", "AS", "AT", "AU",
//        "AW", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BM",
//        "BN", "BO", "BQ", "BR", "BS", "BT", "BW", "BY", "BZ", "CA", "CC", "CD",
//        "CF", "CH", "CI", "CK", "CL", "CM", "CN", "CO", "CR", "CU", "CV", "CW",
//        "CY", "CZ", "DE", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "ES", "ET",
//        "FI", "FJ", "FK", "FO", "FR", "GB", "GD", "GE", "GF", "GG", "GH", "GI",
//        "GL", "GN", "GP", "GQ", "GR", "GS", "GT", "GU", "GW", "GY", "HK", "HN",
//        "HR", "HT", "HU", "ID", "IE", "IL", "IM", "IN", "IO", "IQ", "IR", "IS",
//        "IT", "JE", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KP",
//        "KR", "KW", "KY", "KZ", "LB", "LC", "LI", "LK", "LT", "LU", "LV", "LY",
//        "MA", "MC", "MD", "ME", "MG", "MK", "MM", "MN", "MO", "MQ", "MT", "MU",
//        "MW", "MX", "MY", "MZ", "NA", "NC", "NF", "NG", "NI", "NL", "NO", "NP",
//        "NZ", "OM", "PA", "PE", "PF", "PH", "PK", "PL", "PM", "PR", "PS", "PT",
//        "PY", "QA", "RE", "RO", "RS", "RU", "RW", "SA", "SC", "SD", "SE", "SG",
//        "SH", "SI", "SK", "SL", "SM", "SN", "SO", "SR", "ST", "SV", "SY", "SZ",
//        "TC", "TF", "TG", "TH", "TJ", "TM", "TN", "TO", "TR", "TT", "TW", "TZ",
//        "UA", "UG", "UM", "US", "UY", "UZ", "VA", "VC", "VE", "VI", "VN", "VU",
//        "WF", "XK", "YE", "YT", "ZM", "ZW"
//    )