package com.example.radioplayer.utils

data class Language (
    val iso : String,
    val name : String,
    val stationCount : Int
        )


val listOfLanguages = arrayListOf(

    Language("af", "afrikaans", 22),
    Language("ak", "akan", 1),
    Language("sq", "albanian", 25),
    Language("am", "amharic", 4),
    Language("ar", "arabic", 255),
    Language("hy", "armenian", 8),
    Language("ast", "asturian", 1),
    Language("ay", "aymara", 5),
    Language("az", "azerbaijani", 19),
    Language("ba", "bashkir", 2),
    Language("eu", "basque", 15),
    Language("bar", "bavarian", 1),
    Language("be", "belarusian", 22),
    Language("bn", "bengali", 32),
    Language("bs", "bosnian", 28),
    Language("br", "breton", 9),
    Language("bg", "bulgarian", 86),
    Language("my", "burmese", 5),
    Language("yue", "cantonese", 86),
    Language("ca", "catalan", 125),
    Language("zh", "chinese", 2084),
    Language("cv", "chuvash", 1),
    Language("hr", "croatian", 139),
    Language("cs", "czech", 151),
    Language("da", "danish", 98),
    Language("nl", "dutch", 458),
    Language("dz", "dzongkha", 1),
    Language("en", "english", 8568),
    Language("eo", "esperanto", 2),
    Language("et", "estonian", 37),
    Language("fo", "faroese", 6),
    Language("fj", "fijian", 3),
    Language("fi", "finnish", 95),
    Language("fr", "french", 2000),
    Language("gd", "gaelic", 7),
    Language("gl", "galician", 22),
    Language("ka", "georgian", 12),
    Language("de", "german", 3266),
    Language("el", "greek", 1246),
    Language("gn", "guarani", 3),
    Language("gu", "gujarati", 1),
    Language("hak", "hakka", 5),
    Language("ha", "hausa", 9),
    Language("he", "hebrew", 57),
    Language("hi", "hindi", 115),
    Language("hu", "hungarian", 187),
    Language("is", "icelandic", 19),
    Language("id", "indonesian", 121),
    Language("iu", "inuktitut", 1),
    Language("ga", "irish", 8),
    Language("it", "italian", 1152),
    Language("ja", "japanese", 96),
    Language("jv", "javanese", 3),
    Language("kl", "kalaallisut", 1),
    Language("kn", "kannada", 3),
    Language("kk", "kazakh", 17),
    Language("km", "khmer", 9),
    Language("rw", "kinyarwanda", 2),
    Language("ko", "korean", 78),
    Language("ku", "kurdish", 27),
    Language("la", "latin", 8),
    Language("lv", "latvian", 40),
    Language("ln", "lingala", 2),
    Language("lt", "lithuanian", 45),
    Language("nds", "low german", 19),
    Language("dsb", "lower sorbian", 1),
    Language("lb", "luxembourgish", 15),
    Language("mk", "macedonian", 11),
    Language("mg", "malagasy", 8),
    Language("ms", "malay", 19),
    Language("ml", "malayalam", 41),
    Language("mt", "maltese", 10),
    Language("cmn", "mandarin", 23),
    Language("gv", "manx", 1),
    Language("mr", "marathi", 5),
    Language("mn", "mongolian", 15),
    Language("ne", "nepali", 18),
    Language("no", "norwegian", 87),
    Language("oc", "occitan", 11),
    Language("os", "ossetian", 2),
    Language("fa", "persian", 31),
    Language("pl", "polish", 699),
    Language("pt", "portuguese", 588),
    Language("qu", "quechua", 6),
    Language("ro", "romanian", 314),
    Language("rm", "romansh", 2),
    Language("ru", "russian", 982),
    Language("sa", "sanskrit", 2),
    Language("sc", "sardinian", 1),
    Language("sr", "serbian", 236),
    Language("sd", "sindhi", 2),
    Language("si", "sinhala", 26),
    Language("sk", "slovak", 95),
    Language("sl", "slovenian", 62),
    Language("so", "somali", 2),
    Language("es", "spanish", 3217),
    Language("swg", "swabian", 1),
    Language("sw", "swahili", 22),
    Language("sv", "swedish", 122),
    Language("gsw", "swiss german", 41),
    Language("tl", "tagalog", 13),
    Language("ty", "tahitian", 2),
    Language("tg", "tajik", 3),
    Language("ta", "tamil", 67),
    Language("tt", "tatar", 5),
    Language("te", "telugu", 9),
    Language("th", "thai", 59),
    Language("bo", "tibetan", 14),
    Language("tr", "turkish", 154),
    Language("tk", "turkmen", 10),
    Language("uk", "ukrainian", 123),
    Language("hsb", "upper sorbian", 1),
    Language("ur", "urdu", 45),
    Language("uz", "uzbek", 5),
    Language("vi", "vietnamese", 31),
    Language("cy", "welsh", 7),
    Language("xh", "xhosa", 4),
    Language("yi", "yiddish", 3)
)